import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import StoreProvider from "./StoreProvider";
import "@/styles/globals.css";
import 'react-photo-view/dist/react-photo-view.css';

import Header from "@/app/ui/header"
import ToolList from "./ui/toolList"
import { getUserInfoData } from "@/app/lib/api";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 获取用户数据
  const userInfoData = await getUserInfoData();

  return (
    <html data-theme="lofi" lang="zh">
      <body>
        <StoreProvider userinfo={userInfoData}>
          <Toaster />
          <div className="drawer lg:drawer-open overflow-hidden">
            <input id="jugg-global-drawer" type="checkbox" className="drawer-toggle" />

            <div className="drawer-side border-r z-20 lg:z-0">
              <label htmlFor="jugg-global-drawer" aria-label="close sidebar" className="drawer-overlay"></label>
              <ToolList />
            </div>

            <div className="drawer-content items-center bg-primary-content h-svh overflow-hidden relative">
              {/* Page content here */}
              <Header />
              <main id="main" className="w-full min-h-full overflow-y-auto pt-16 absolute inset-0">
                {children}
              </main>
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
